add Tail-kit Components Kit
aniftyco/awesome-tailwindcss pull request #343
Opened 2021-01-20 10:40 UTC by Charlie85270

| Name                 | Link                 |
| -------------------- | -------------------- |
| Tail-kit | https://tailwind-kit.com |

Tail-kit, a free and open source components Kit based on Tailwind CSS 2.0.

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] I have read and followed the [contribution guidelines](.github/CONTRIBUTING.md)

2021-01-20 11:26 UTC, innocenzi reviewed
Related to the name (I see `Tailwind UI Kit` in the title of your site), I'd like to get @joshmanders' approval before merging this.

2021-01-20 11:26 UTC, innocenzi commented on README.md
> +- 🧩 [Tail-kit](https://tailwind-kit.com/) - 200+ fully coded, free and open source components.
```suggestion
- 🧩 [Tail-kit](https://tailwind-kit.com/) - 200+ free and open-source components.
```

2021-01-20 16:08 UTC, tonyketcham commented
This looks fantastic

2021-01-20 16:47 UTC, joshmanders commented
I've consulted with Adam about the naming of this project, once his verdict comes back I'll update.

2021-01-20 16:57 UTC, joshmanders requested changes

2021-01-20 16:57 UTC, joshmanders commented on README.md
> +- 🧩 [Tail-kit](https://tailwind-kit.com/) - 200+ free and open-source components.
After talking with Adam, the domain still violates brand usage guidelines. Once that is resolved and we don't see any violations of the [Tailwind Brand Usage Guidelines](https://tailwindcss.com/brand#usage), we'll happily accept the PR.

2021-01-30 15:01 UTC, joshmanders commented
Closing as no response in 10 days.

2021-01-30 15:01 UTC, closed without merging