Update README.md
aniftyco/awesome-tailwindcss pull request #371
Opened 2021-03-22 04:45 UTC by Thomashighbaugh

| Name                 | Link                 |
| -------------------- | -------------------- |
| _Resource name here_ | _Resource link here_ |

_Resource description here_

---

- [ ] My item is in the right category
- [ ] My item is logically grouped below similar items
- [ ] My item's name and description respects the conventions of the list
- [ ] My item is awesome
- [ ] I have read and followed the [contribution guidelines](.github/CONTRIBUTING.md)

2021-03-22 12:37 UTC, innocenzi requested changes
Can you respect the template and re-read the contributions guidelines please?

2021-03-23 07:41 UTC, Thomashighbaugh commented
I am sorry, I hadn't noticed the guidelines were linked, as it was not listed in the table of contents and only found it after searching the page for text. 

Upon reviewing the guidelines, I adjusted the entry by capitalizing the name of the repository and conforming to the form of `Tailwind CSS` ennumerated in the guidelines. Sorry about that, just didn't see didn't mean to disrespect anything...

2021-03-23 08:43 UTC, innocenzi approved these changes

2021-03-23 08:45 UTC, merged

2021-03-23 08:45 UTC, innocenzi commented
All good, no worries. By template, I meant the message of your PR. You didn't edit the placeholders nor did you check the list items, which are here so you can verify that your submission contributes to the list. 

I'm not sure if we need a second resume template on the list, but let's add it for now. :+1: