Add Tailwindcomponents Cheatsheet
aniftyco/awesome-tailwindcss pull request #382
Opened 2021-05-21 11:38 UTC by khatabwedaa

| Name                 | Link                 |
| -------------------- | -------------------- |
| _Tailwindcomponents cheatsheet_ | _https://tailwindcomponents.com/cheatsheet_ |

_Tailwind CSS cheat sheet helps you to discover Tailwind CSS utilities_

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

2021-05-22 16:38 UTC, innocenzi requested changes
The description doesn't respect the guidelines.

2021-05-22 16:38 UTC, innocenzi commented
@joshmanders I just realized the name of this project doesn't respect the usage allowed by Tailwind Labs (https://tailwindcss.com/brand) - do we have to delete each item from the list with this domain name? 

@khatabwedaa I noticed you have a brand, Highscore Studio, in the copyright of your project's site. Shouldn't you use that in place of `tailwindcomponents.com`?

2021-05-22 19:26 UTC, joshmanders commented
> do we have to delete each item from the list with this domain name?

That's a good question, let me confer with Adam.

2021-05-23 07:42 UTC, khatabwedaa commented
@innocenzi what I have to change?

2021-05-23 09:50 UTC, innocenzi commented on README.md
> +- 🌍 [Tailwindcomponents Cheatsheet](https://tailwindcomponents.com/cheatsheet) - Tailwind CSS cheat sheet helps you to discover Tailwind CSS utilities.
```suggestion
- 🌍 [Tailwind Cheat Sheet](https://tailwindcomponents.com/cheatsheet) - Tailwind CSS class names in a searchable page.
```

2021-05-23 09:51 UTC, innocenzi approved these changes

2021-05-23 09:51 UTC, merged

2021-05-23 09:52 UTC, innocenzi commented
Changed it for you

2021-05-23 13:23 UTC, khatabwedaa commented
Thanks 👍