Added OhMySMTP Templates to the list of templates
aniftyco/awesome-tailwindcss pull request #406
Opened 2021-09-27 19:22 UTC by paul-oms

| Name                 | Link                 |
| -------------------- | -------------------- |
| OhMySMTP Templates|https://github.com/ohmysmtp/templates|

A set of Transactional HTML Email Templates, built with Tailwind CSS and Maizzle

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

2021-09-27 19:50 UTC, innocenzi requested changes
Pretty nice work! Please update the description to abide to the [guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md#formats-naming-conventions-and-descriptions) and I can merge this :)

2021-09-28 07:29 UTC, paul-oms commented
Thanks @innocenzi - updated the description - hope it's ok now? Thanks!

2021-09-28 08:08 UTC, innocenzi commented on README.md
> +- 📁 [OhMySMTP Templates](https://github.com/ohmysmtp/templates) - Set of Transactional HTML Email Templates, built with Maizzle
```suggestion
- 📁 [OhMySMTP Templates](https://github.com/ohmysmtp/templates) - Set of transactional HTML email templates, built with Maizzle.
```

2021-09-28 08:08 UTC, innocenzi approved these changes

2021-09-28 08:08 UTC, merged

2021-09-28 08:08 UTC, innocenzi commented
Almost, but I updated it myself. Thanks!