Add a new UI library for Tailwind CSS
aniftyco/awesome-tailwindcss pull request #461
Opened 2022-08-28 16:43 UTC by sidiDev

| Name                 | Link                 |
| -------------------- | -------------------- |
Float UI                floatui.com

I just added a new UI ibrary for Tailwind CSS in UI Libraries, Components & Templates category, and hope you like it.

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

2022-08-28 17:00 UTC, innocenzi requested changes
Please use an actual URL as the link, shorten the description if possible, fix the brand names in your description, place the project at the end of the emoji category and update the PR title to fit the contribution guidelines.

2022-08-28 19:55 UTC, sidiDev commented
> Please use an actual URL as the link, shorten the description if possible, fix the brand names in your description, place the project at the end of the emoji category and update the PR title to fit the contribution guidelines.

2022-08-28 19:56 UTC, sidiDev commented
> Please use an actual URL as the link, shorten the description if possible, fix the brand names in your description, place the project at the end of the emoji category and update the PR title to fit the contribution guidelines.

Hi @innocenzi ! That's done, you can check it out now.

2022-08-29 14:15 UTC, joshmanders commented
@sidiDev 
> Hi @innocenzi ! That's done, you can check it out now.

You closed the PR.

2022-08-29 14:22 UTC, sidiDev commented
> @sidiDev
> 
> > Hi @innocenzi ! That's done, you can check it out now.
> 
> You closed the PR.

Yeah, you're right, I'm sorry for that, it was a mistake, I reopen it.

2022-10-18 17:18 UTC, joshmanders commented
I just noticed this was still open. If it looks good to you @innocenzi I'll merge.

2022-10-18 17:23 UTC, innocenzi commented on README.md
> +- 🧩 [Float UI](https://floatui.com) - UI components with Tailwind even with pure CSS, support both directions LTR and RTL.
```suggestion
- 🧩 [Float UI](https://floatui.com) - UI components with Tailwind CSS even with pure CSS, with LTR and RTL support.
```

2022-10-18 17:23 UTC, innocenzi approved these changes

2022-10-18 17:24 UTC, innocenzi requested changes
I updated the description - but please move the entry below other components (Daisy UI)

2022-10-18 17:25 UTC, joshmanders commented
@sidiDev address the request by @innocenzi and we'll get this merged in.

2022-11-06 17:11 UTC, joshmanders commented
Closed because this PR was abandoned.

2022-11-06 17:11 UTC, closed without merging