add(tools): Tailwindhelper
aniftyco/awesome-tailwindcss pull request #464
Opened 2022-09-25 12:11 UTC by felixmacaspac

| Name                 | Link                 |
| -------------------- | -------------------- |
| _Resource name here_ | _Resource link here_ |

_Resource description here_
A tool that helps you visualize Tailwind CSS classes and also a unit converter. 
---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

2022-09-25 12:19 UTC, basarozcan commented
That domain name is NOT in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)

2022-09-28 17:00 UTC, joshmanders commented
Hey @felixmacaspac while I feel it doesn't fall in line with the guidelines either, it's a cool and useful site. I've reached out to Adam on what he thinks and I'll let ya know. If he would like it to follow guidelines I'd suggest getting a different domain and rebranding, but I'd love to have this as an added entry in the repo!

2022-09-28 17:01 UTC, joshmanders requested changes

2022-09-28 17:01 UTC, joshmanders commented on README.md
> +- 🔼🌍🔧 [Tailwindhelper](https://www.tailwindhelper.com/) - Visualize Tailwind CSS classes and unit converter.
Awaiting feedback from Adam about the domain following guidelines, but I'd like to see it rebranded and updated. We can merge it in after that :)

2022-09-28 19:43 UTC, joshmanders approved these changes
Adam has said this is fine as it's just a free helpful thing, so if you do decide to monetize it in any way, you'll be in violation of the guidelines. So be sure to be aware of that, as it'll be my job to make sure we don't support violations in this repo.

2022-09-28 19:43 UTC, merged

2022-09-28 20:43 UTC, felixmacaspac commented
Hi @joshmanders thanks for including it in the repo, **BUT** this is not my own work nor affiliated with it. I just found this open source tool on GitHub and was using it frequently, I just thought it was an incredible tool which is why I added it here. Would there be any problem if I'm not the owner of this tool? Sorry, I didn't expect that it would be approved because I also just realized that recently.

2022-09-28 21:36 UTC, joshmanders commented
@felixmacaspac oh nah don't sweat it, contributions are allowed from anyone, we just kind of assumed it was yours because most people who are submitting are doing so to share something they made. I'll reach out to the dev!

2022-09-28 21:52 UTC, joshmanders commented
Shared with the creator: https://github.com/Seb-GRAF/tailwind-helper/issues/2