Update README.md
aniftyco/awesome-tailwindcss pull request #511
Opened 2023-07-14 22:09 UTC by diomed

added 2 UI libraries
removed few dead and outdated [archived] links| Name                 | Link                 |
| -------------------- | -------------------- |
| _Resource name here_ | _Resource link here_ |

_Resource description here_

---

- [ ] My item is in the right category
- [ ] My item is logically grouped below similar items
- [ ] My item's name and description respects the conventions of the list
- [ ] My item is awesome
- [ ] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [ ] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

2023-07-18 15:24 UTC, joshmanders requested changes
Other than these I don't see anything wrong. What do you think @innocenzi?

2023-07-18 15:24 UTC, joshmanders commented on README.md
> +- 🧩 [Pines UI](https://devdojo.com/pines) - Alpine and Tailwind CSS UI library
```suggestion
- 🧩 [Pines UI](https://devdojo.com/pines) - Alpine and Tailwind CSS UI library.
```

2023-07-18 15:24 UTC, joshmanders commented on README.md
> +- 🚀 [Tailwind sites](https://tailwindsites.com) - Free Tailwind CSS site templates for your next project
```suggestion
- 🚀 [Tailwind sites](https://tailwindsites.com) - Free Tailwind CSS site templates for your next project.
```

2023-07-19 13:03 UTC, innocenzi approved these changes
LGTM after the changes asked by @joshmanders 👍

2023-07-19 14:13 UTC, joshmanders approved these changes

2023-07-19 14:13 UTC, merged