Add Float UI
aniftyco/awesome-tailwindcss pull request #512
Opened 2023-07-23 00:35 UTC by Yaya12085

| Name                 | Link                 |
| -------------------- | -------------------- |
| Float UI | https://floatui.com |

_Resource description here_
UI components for React and Vue (soon) with Tailwind, every example support both directions LTR and RTL.
---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

2023-07-23 15:16 UTC, innocenzi requested changes
Please update the description and PR title to follow the contribution guidelines, and update the emojis to better fit the item.

2023-07-23 23:34 UTC, joshmanders requested changes

2023-07-23 23:34 UTC, joshmanders commented on README.md
> +- 🧩📁 [Float UI](https://floatui.com/) - Components and templates made with Tailwind CSS, supporting both LTR and RTL directions.
Please revert all changes except this line.

2023-08-09 14:56 UTC, closed without merging

2023-08-09 14:57 UTC, joshmanders commented
Closed due to no response.