Add tailwindcsscolors.com, tailwindgradients.com and fullwindcss.com
aniftyco/awesome-tailwindcss pull request #559
Opened 2024-05-03 05:18 UTC by ErwinAI

| Name                 | Link                 |
| -------------------- | -------------------- |
| TailwindCssColors | tailwindcsscolors.com |
| TailwindGradients | tailwindgradients.com |
| Fullwind CSS| fullwindcss.com |

Color palete cheatsheet, gradient collection and extended shades for the default palette.

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

2024-05-03 18:19 UTC, innocenzi requested changes

2024-05-03 18:19 UTC, innocenzi commented on README.md
> +- 🎨🌍🔧 [Tailwind CSS Colors](http://tailwindcsscolors.com) - Cheat sheet for Tailwind Colors with easy copying in various formats.
```suggestion
- 🎨🌍🔧 [Tailwind CSS Colors](http://tailwindcsscolors.com) - Cheat sheet for Tailwind CSS colors.
```

2024-05-03 18:19 UTC, innocenzi commented on README.md
> +- 🎨🌍🔧 [Tailwind Gradients](http://tailwindgradients.com) - Collection of Tailwind gradients, easy to browse and one-click copy.
```suggestion
- 🎨🌍🔧 [Tailwind Gradients](http://tailwindgradients.com) - Collection of gradients using Tailwind CSS classes.
```

2024-05-03 18:19 UTC, innocenzi commented on README.md
> +- 🎨🌍🔧 [Fullwind CSS](https://fullwindcss.com/) - Additional shades for the Tailwind CSS Color palette.
```suggestion
- 🎨🌍🔧 [Fullwind CSS](https://fullwindcss.com/) - Extend Tailwind CSS color palettes with additional shades.
```

2024-05-06 08:23 UTC, innocenzi approved these changes

2024-05-06 08:24 UTC, merged

2024-05-16 16:42 UTC, laurentlahmy commented
😍 Thanks Erwin!