Added Flyon UI Component Library
aniftyco/awesome-tailwindcss pull request #575
Opened 2024-10-02 10:01 UTC by abhidave001

| Name                 | Link                 |
| -------------------- | -------------------- |
| _Flyon UI_ | _https://flyonui.com/_ |

[FlyonUI](https://flyonui.com/) is designed to combine the best of both worlds: the aesthetic appeal of semantic classes and the powerful functionality of JS plugins.

It has over 78+ components & examples & built with DaisyUI & Preline.

**Features:**

- 800+ Free Components & Examples
- Universal Framework Compatibility
- Unlimited Themes 
- Unstyled & Accessible Plugins
- Responsive & RTL support
- Free Forever
- Beautiful and Semantic Styling
- Efficiency and Productivity
- Maintainable and Scalable

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

2024-10-02 17:45 UTC, innocenzi commented
Hello, please group it properly 👍

2024-10-02 21:04 UTC, joshmanders requested changes

2024-10-02 21:04 UTC, joshmanders commented on README.md
> +- 📚🧩[Flyon UI Tailwind Components Library](https://flyonui.com/) - The Easiest Components Library For Tailwind CSS.
```suggestion
- 📚🧩[Flyon UI](https://flyonui.com/) - Component Library For Tailwind CSS.
```

2024-10-04 05:52 UTC, abhidave001 commented
> Hello, please group it properly 👍

Hi,
May I know how to group it?

I mean I have added the product in the section: UI Libraries, Components & Templates
Should it be mentioned after Preline?

![image](https://github.com/user-attachments/assets/2f8c5c42-20fc-4563-8951-889775e2a1fb)

2024-10-04 11:42 UTC, innocenzi commented on README.md
> +- 📚🧩[Flyon UI Tailwind Components Library](https://flyonui.com/) - Open Source Components Library For Tailwind CSS.
```suggestion
- 📚🧩[Flyon UI](https://flyonui.com/) - Open-source components library for Tailwind CSS.
```

2024-10-04 11:43 UTC, innocenzi approved these changes

2024-10-04 11:46 UTC, innocenzi commented
> as suggested by the authorities 

lol—you checked "I have read and followed the contribution guidelines", but still didn't:
- Place your item correctly
- Name your pull request correctly
- Name your item correctly
- Name the description correctly

We just want to keep the list clean, man. Thanks for the contribution 🫠

2024-10-04 13:59 UTC, abhidave001 commented
> > as suggested by the authorities
> 
> lol—you checked "I have read and followed the contribution guidelines", but still didn't:
> 
> * Place your item correctly
> * Name your pull request correctly
> * Name your item correctly
> * Name the description correctly
> 
> We just want to keep the list clean, man. Thanks for the contribution 🫠
> 
> @joshmanders I think GitHub needs your re-approval before we can merge

Pardon me for the mistakes.

I did actually read the guidelines but thing is I wasn't sure about the title as mostly I have written short desc. of what I have added in the list whenever I submit the product. 

This is the case of misunderstanding from my end. 
I'll take care from now onwards.

Btw, Do I need to do anything from my end again?
Let me know.

2024-10-04 14:36 UTC, innocenzi commented
All good—just missing Josh's approval, due to the previous request changes

2024-10-04 22:22 UTC, joshmanders approved these changes
> as suggested by the authorities

BOW TO ME, PEASANTS FOR I AM THE COMMANDER OF ALL AUTHORITY!

Just kidding, if Enzo says it's good, I think it's good to. Welcome to the list.

2024-10-04 22:22 UTC, merged

2024-10-07 10:48 UTC, abhidave001 commented
> > as suggested by the authorities
> 
> BOW TO ME, PEASANTS FOR I AM THE COMMANDER OF ALL AUTHORITY!
> 
> Just kidding, if Enzo says it's good, I think it's good to. Welcome to the list.

Thanks a lot for adding the resource. 👍🏻